name: web-app build & test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flask
          if [ -f ./web-app/requirements.txt ]; then pip install -r ./web-app/requirements.txt; fi
      - name: 'Create env file'
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env
      - name: Test with pytest
        run: |
          python -m pytest web-app/tests
      - name: Log in to Docker Hub
        run: |
            docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build the Docker image
        run: |
            docker build . --file Dockerfile --tag ${{ steps.meta.outputs.tags }} --label ${{ steps.meta.outputs.labels }}
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/se_final_project
